#spring:
#  profiles:
#    active: local # 기본 환경 선택
#
## local 환경
#---
spring:
#  profiles:
#    include: oauth
#  datasource:
#    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    defer-datasource-initialization: true
  # 웹 콘솔 활성화
  h2:
    console:
      enabled: true